# Generated by Django 4.0.5 on 2023-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=60)),
                ('price1', models.IntegerField()),
                ('price2', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
