# Generated by Django 4.0.5 on 2023-12-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='color',
            field=models.CharField(default='red', max_length=30),
            preserve_default=False,
        ),
    ]
