# Generated by Django 4.0.5 on 2023-12-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0002_fridge_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='door_color',
            field=models.CharField(default='white', max_length=30),
        ),
    ]
