# Generated by Django 4.0.5 on 2023-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0003_fridge_door_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='old_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
