# Generated by Django 4.0.5 on 2023-12-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0004_fridge_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='adad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridge',
            name='string',
            field=models.CharField(default='salam', max_length=30),
            preserve_default=False,
        ),
    ]
