# Generated by Django 4.0.5 on 2023-12-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0005_fridge_adad_fridge_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='adad_koorosh',
            field=models.SmallIntegerField(default=9999999999999999),
        ),
    ]
