# Generated by Django 4.0.5 on 2023-12-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fridge', '0006_fridge_adad_koorosh'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='adad_koorosh2',
            field=models.SmallIntegerField(default=999999999999999999999999999999999999999),
        ),
    ]
