# Generated by Django 4.0.5 on 2023-12-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
